from test.ConfigTests import ConfigTests
from test.IngredientTests import IngredientTests
from test.CoffeeRecipeTests import CoffeeRecipeTests
from test.CoffeePreparationTests import CoffeePreparationTests
from test.AuthControllerTests import AuthControllerTests
from test.EnvironmentControllerTests import EnvironmentControllerTests
from test.MainTests import MainTests
