DROP TABLE IF EXISTS Temperature;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Ingredient;
DROP TABLE IF EXISTS CoffeePreparation;
DROP TABLE IF EXISTS CoffeeRecipe;
DROP TABLE IF EXISTS CoffeeRecipeIngredient;
DROP TABLE IF EXISTS Log;