INSERT INTO Ingredient (name, measure_unit, available) VALUES ('water', 'ml', 500);
INSERT INTO Ingredient (name, measure_unit, available) VALUES ('milk', 'ml', 300);
INSERT INTO Ingredient (name, measure_unit, available) VALUES ('sugar', 'gr', 350);
INSERT INTO Ingredient (name, measure_unit, available) VALUES ('cocoa', 'gr', 200);
INSERT INTO Ingredient (name, measure_unit, available) VALUES ('whipped cream', 'ml', 100);
INSERT INTO Ingredient (name, measure_unit, available) VALUES ('syrup', 'ml', 50);
INSERT INTO Ingredient (name, measure_unit, available) VALUES ('whiskey', 'ml', 30);
INSERT INTO Ingredient (name, measure_unit, available) VALUES ('coffee', 'gr', 400);

INSERT INTO CoffeeRecipe (name, preparation_time) VALUES ('Irish Coffee', 1);
INSERT INTO CoffeeRecipe (name, preparation_time) VALUES ('Hot Chocolate', 0.5);
INSERT INTO CoffeeRecipe (name, preparation_time) VALUES ('Short Espresso', 0.25);
INSERT INTO CoffeeRecipe (name, preparation_time) VALUES ('Long Espresso', 1.25);
INSERT INTO CoffeeRecipe (name, preparation_time) VALUES ('Cappuccino', 0.75);
INSERT INTO CoffeeRecipe (name, preparation_time) VALUES ('Caramel Frappe', 2);
INSERT INTO CoffeeRecipe (name, preparation_time) VALUES ('Mocha', 1.75);

INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (1, 5, 50);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (1, 7, 10);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (1, 8, 50);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (2, 4, 100);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (2, 1, 250);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (2, 3, 50);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (3, 8, 150);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (3, 1, 50);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (4, 8, 50);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (4, 1, 150);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (5, 8, 100);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (5, 2, 200);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (6, 6, 30);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (6, 3, 50);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (6, 5, 50);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (6, 2, 300);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (6, 8, 50);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (7, 8, 50);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (7, 2, 200);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (7, 5, 50);
INSERT INTO CoffeeRecipeIngredient (recipe_id, ingredient_id, quantity) VALUES (7, 4, 80);
